version: "3.9"

services:
  network-topology-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: network-topology-service:latest
    container_name: network-topology-service
    env_file:
      - settings.local.env
    volumes:
      - ./certs:/home/uttam/Documents/workspace/openwifi/ra-openlan-nw-topology/certs:ro
    ports:
      - "8088:8088"
    restart: unless-stopped
